// Generated by gencpp from file common/RemoteControlMsg.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_REMOTECONTROLMSG_H
#define COMMON_MESSAGE_REMOTECONTROLMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common
{
template <class ContainerAllocator>
struct RemoteControlMsg_
{
  typedef RemoteControlMsg_<ContainerAllocator> Type;

  RemoteControlMsg_()
    : header()
    , status(0)
    , leftwheel(0)
    , rightwheel(0)  {
    }
  RemoteControlMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(0)
    , leftwheel(0)
    , rightwheel(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _status_type;
  _status_type status;

   typedef int32_t _leftwheel_type;
  _leftwheel_type leftwheel;

   typedef int32_t _rightwheel_type;
  _rightwheel_type rightwheel;



  enum {
    REMOTE = 0u,
    AUTONOMOUS = 1u,
  };


  typedef boost::shared_ptr< ::common::RemoteControlMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::RemoteControlMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RemoteControlMsg_

typedef ::common::RemoteControlMsg_<std::allocator<void> > RemoteControlMsg;

typedef boost::shared_ptr< ::common::RemoteControlMsg > RemoteControlMsgPtr;
typedef boost::shared_ptr< ::common::RemoteControlMsg const> RemoteControlMsgConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::RemoteControlMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::RemoteControlMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'common': ['/home/pi/Desktop/Robots/rpi_vehicle/src/common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common::RemoteControlMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::RemoteControlMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::RemoteControlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::RemoteControlMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::RemoteControlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::RemoteControlMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::RemoteControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23c6596709461c8678d41a4214a56d44";
  }

  static const char* value(const ::common::RemoteControlMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23c6596709461c86ULL;
  static const uint64_t static_value2 = 0x78d41a4214a56d44ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::RemoteControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/RemoteControlMsg";
  }

  static const char* value(const ::common::RemoteControlMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::RemoteControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 status\n\
uint8 REMOTE = 0\n\
uint8 AUTONOMOUS = 1\n\
\n\
# -100 means backward in max speed.\n\
# +100 means forward in max speed.\n\
int32 leftwheel\n\
int32 rightwheel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::common::RemoteControlMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::RemoteControlMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.leftwheel);
      stream.next(m.rightwheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoteControlMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::RemoteControlMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::RemoteControlMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "leftwheel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leftwheel);
    s << indent << "rightwheel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rightwheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_REMOTECONTROLMSG_H
